### ISSUE TITLE
全文索引panic

### ISSUE THREAD

**Issue by hoffermei** [Tencent/bk-cmdb#2768]
问题描述
===========
基于es的全文索引查询时panic

```
E0719 17:16:08.106143   48338 operation/object.go:338] get model failed, get model by supplier account(0) objects(biz) not found, result: [], rid: cc0000bkookm6v50ubour1dmg0
E0719 17:16:08.106894   48338 service/inst_business.go:248] failed to search the business, 未找到相关数据, rid: cc0000bkookm6v50ubour1dmg0
E0719 17:16:08.119271   48338 operation/object.go:338] get model failed, get model by supplier account(0) objects(biz) not found, result: [], rid: cc0000bkookm6v50ubour1dmh0
E0719 17:16:08.119308   48338 service/association.go:108] [api-asst] failed to find the biz object, error info is 未找到相关数据, rid: cc0000bkookm6v50ubour1dmh0
E0719 17:16:08.686883   48338 operation/object.go:338] get model failed, get model by supplier account(0) objects(biz) not found, result: [], rid: cc0000bkookm6v50ubour1dmhg
E0719 17:16:08.686917   48338 service/inst_business.go:248] failed to search the business, 未找到相关数据, rid: cc0000bkookm6v50ubour1dmhg
E0719 17:19:54.709651   48338 rdapi/rdfunc.go:50] server panic, err:"invalid memory address or nil pointer dereference", rid:cc0000bkoomemv50ubour1dngg, debug strace:goroutine 214 [running]:
runtime/debug.Stack(0xc000c2a0c0, 0x1d0403c, 0xd)
        /usr/local/Cellar/go/1.12.3/libexec/src/runtime/debug/stack.go:24 +0x9d
configcenter/src/common/rdapi.AllGlobalFilter.func1.1(0xc000c2a210, 0xc000dd6250, 0xc000a7aa80)
        /Users/hoffermei/cmdb-workspace/cmdb-hoffermei/src/configcenter/src/common/rdapi/rdfunc.go:50 +0xb1
panic(0x1b8e440, 0x27bd0e0)
        /usr/local/Cellar/go/1.12.3/libexec/src/runtime/panic.go:522 +0x1b5
sync.(*RWMutex).RLock(...)
        /usr/local/Cellar/go/1.12.3/libexec/src/sync/rwmutex.go:48
configcenter/vendor/github.com/olivere/elastic.(*Client).PerformRequest(0x0, 0x1f4ef20, 0xc0000c2008, 0x1cfc26c, 0x4, 0xc00042a300, 0x29, 0xc000c2a870, 0x1b6b300, 0xc000c2a8a0, ...)
        /Users/hoffermei/cmdb-workspace/cmdb-hoffermei/src/configcenter/vendor/github.com/olivere/elastic/client.go:1253 +0xea
configcenter/vendor/github.com/olivere/elastic.(*SearchService).Do(0xc000c131e8, 0x1f4ef20, 0xc0000c2008, 0x8, 0xc000a762d8, 0x2)
        /Users/hoffermei/cmdb-workspace/cmdb-hoffermei/src/configcenter/vendor/github.com/olivere/elastic/search.go:437 +0x121
configcenter/src/thirdpartyclient/elasticsearch.(*EsSrv).CmdbSearch(0xc000010060, 0x1f33100, 0xc000101b80, 0xc00000ea40, 0x2, 0x2, 0x0, 0xa, 0x1bb41e0, 0xc000260090, ...)
        /Users/hoffermei/cmdb-workspace/cmdb-hoffermei/src/configcenter/src/thirdpartyclient/elasticsearch/esclient.go:93 +0x882
configcenter/src/scene_server/topo_server/service.(*Service).FullTextFind(0xc0001ce1a0, 0x1f4efa0, 0xc000c2a3c0, 0xc0002de580, 0xc000c2a0c0, 0x7, 0x2787ab0, 0x1, 0xc0001ad1f0, 0x5, ...)
        /Users/hoffermei/cmdb-workspace/cmdb-hoffermei/src/configcenter/src/scene_server/topo_server/service/find.go:69 +0x2ba
configcenter/src/scene_server/topo_server/service.(*Service).Actions.func1.1(0xc000c2a210, 0xc000a7aa80)
        /Users/hoffermei/cmdb-workspace/cmdb-hoffermei/src/configcenter/src/scene_server/topo_server/service/service.go:270 +0x8a1
configcenter/vendor/github.com/emicklei/go-restful.(*Container).dispatch.func6(0xc000c2a210, 0xc000a7aa80)
        /Users/hoffermei/cmdb-workspace/cmdb-hoffermei/src/configcenter/vendor/github.com/emicklei/go-restful/container.go:244 +0x3e
configcenter/vendor/github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc000c2a2a0, 0xc000c2a210, 0xc000a7aa80)
        /Users/hoffermei/cmdb-workspace/cmdb-hoffermei/src/configcenter/vendor/github.com/emicklei/go-restful/filter.go:21 +0x84
configcenter/src/common/rdapi.AllGlobalFilter.func1(0xc000c2a210, 0xc000a7aa80, 0xc000c2a2a0)
        /Users/hoffermei/cmdb-workspace/cmdb-hoffermei/src/configcenter/src/common/rdapi/rdfunc.go:83 +0x276
configcenter/vendor/github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc000c2a2a0, 0xc000c2a210, 0xc000a7aa80)
        /Users/hoffermei/cmdb-workspace/cmdb-hoffermei/src/configcenter/vendor/github.com/emicklei/go-restful/filter.go:19 +0x5e
configcenter/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc000cf2990, 0x1f47720, 0xc000a7a960, 0xc0001d4200)
        /Users/hoffermei/cmdb-workspace/cmdb-hoffermei/src/configcenter/vendor/github.com/emicklei/go-restful/container.go:246 +0x7dd
net/http.HandlerFunc.ServeHTTP(0xc000dd7bc0, 0x1f47720, 0xc000a7a960, 0xc0001d4200)
        /usr/local/Cellar/go/1.12.3/libexec/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0xc00035a740, 0x1f47720, 0xc000a7a960, 0xc0001d4200)
        /usr/local/Cellar/go/1.12.3/libexec/src/net/http/server.go:2375 +0x1d6
configcenter/vendor/github.com/emicklei/go-restful.Container.ServeHTTP(...)
        /Users/hoffermei/cmdb-workspace/cmdb-hoffermei/src/configcenter/vendor/github.com/emicklei/go-restful/container.go:264
configcenter/src/common/metrics.(*Service).HTTPMiddleware.func1(0x1f486e0, 0xc0001de0e0, 0xc0001d4000)
        /Users/hoffermei/cmdb-workspace/cmdb-hoffermei/src/configcenter/src/common/metrics/metrics.go:142 +0x36d
net/http.HandlerFunc.ServeHTTP(0xc0000fec80, 0x1f486e0, 0xc0001de0e0, 0xc0001d4000)
        /usr/local/Cellar/go/1.12.3/libexec/src/net/http/server.go:1995 +0x44
net/http.serverHandler.ServeHTTP(0xc0000bc270, 0x1f486e0, 0xc0001de0e0, 0xc0001d4000)
        /usr/local/Cellar/go/1.12.3/libexec/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc000c53400, 0x1f4eee0, 0xc0010d7940)
        /usr/local/Cellar/go/1.12.3/libexec/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.12.3/libexec/src/net/http/server.go:2884 +0x2f4
```

关键信息
=========
 - [x] bk-cmdb   版本: v3.5.x

**Comment by hoffermei** [comment]
问题原因：建立escient失败，导致代码异常

E0719 17:43:56.948040   51787 elasticsearch/esclient.go:49] create new http es client error, err: health check timeout: Head http://127.0.0.1:9200: dial tcp 127.0.0.1:9200: connect: connection refused: no Elasticsearch node available
