### ISSUE TITLE
3.10.10版本 前端编译报错

### ISSUE THREAD

**Issue by sswolf** [Tencent/bk-cmdb#5993]
问题描述
===========
3.10.10版本 前端编译报错

cd $GOPATH/src/configcenter/src
make NPM=cnpm

✔ All packages installed (1513 packages installed from npm registry, used 31s(network 28s), speed 702.54KB/s, json 1310(7.42MB), tarball 11.64MB)

> bk-cmdb-ui@1.0.0 build /data/abc/src/configcenter/src/ui
> node builder/build.js "BUILD_OUTPUT=/data/abc/src/configcenter/src/bin/build/v3.10.10"

/data/abc/src/configcenter/src/ui/node_modules/_jest-worker@27.5.1@jest-worker/build/WorkerPool.js:25
  } catch {
          ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/data/abc/src/configcenter/src/ui/node_modules/_jest-worker@27.5.1@jest-worker/build/index.js:38:42)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bk-cmdb-ui@1.0.0 build: `node builder/build.js "BUILD_OUTPUT=/data/abc/src/configcenter/src/bin/build/v3.10.10"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bk-cmdb-ui@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-02-28T07_07_16_410Z-debug.log
make: *** [default] Error 1

重现方法
================
make NPM=cnpm

关键信息
=========

请提供以下信息:

node -v
v8.12.

**Comment by yangyy** [comment]
你好，v3.10.x 版本前端升级为 webpack5 了，需要 Node.js >= 10.13.0 (LTS), npm >= 6.4.1
