### ISSUE TITLE
【3.10.11】编译前端报错SassError: Undefined variable

### ISSUE THREAD

**Issue by hongyuxuan** [Tencent/bk-cmdb#6171]
问题描述
===========
编译前端执行make ui时，报错如下：
```shell
  build [====================] 99% (165.1 seconds)<w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/root/go/src/configcenter/src/ui/node_modules/mini-css-extract-plugin/dist/loader.js!/root/go/src/configcenter/src/ui/node_modules/css-loader/dist/cjs.js??clonedRuleSet-6[0].rules[0].use[1]!/root/go/src/configcenter/src/ui/node_modules/vue-loader/lib/loaders/stylePostLoader.js!/root/go/src/configcenter/src/ui/node_modules/sass-loader/dist/cjs.js??clonedRuleSet-6[0].rules[0].use[2]!/root/go/src/configcenter/src/ui/node_modules/postcss-loader/dist/cjs.js!/root/go/src/configcenter/src/ui/node_modules/sass-resources-loader/lib/loader.js??clonedRuleSet-6[0].rules[0].use[4]!/root/go/src/configcenter/src/ui/node_modules/vue-loader/lib/index.js??vue-loader-options!/root/go/src/configcenter/src/ui/src/components/model-manage/field-group/index.vue?vue&type=style&index=0&id=51830ffa&lang=scss&scoped=true&': No serializer registered for SassError
<w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> webpack/lib/ModuleBuildError -> SassError
<w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'mini-css-extract-plugin /root/go/src/configcenter/src/ui/node_modules/css-loader/dist/cjs.js??clonedRuleSet-6[0].rules[0].use[1]!/root/go/src/configcenter/src/ui/node_modules/vue-loader/lib/loaders/stylePostLoader.js!/root/go/src/configcenter/src/ui/node_modules/sass-loader/dist/cjs.js??clonedRuleSet-6[0].rules[0].use[2]!/root/go/src/configcenter/src/ui/node_modules/postcss-loader/dist/cjs.js!/root/go/src/configcenter/src/ui/node_modules/sass-resources-loader/lib/loader.js??clonedRuleSet-6[0].rules[0].use[4]!/root/go/src/configcenter/src/ui/node_modules/vue-loader/lib/index.js??vue-loader-options!/root/go/src/configcenter/src/ui/src/components/model-manage/field-group/index.vue?vue&type=style&index=0&id=51830ffa&lang=scss&scoped=true&|0|Compilation/modules|/root/go/src/configcenter/src/ui/node_modules/css-loader/dist/cjs.js??clonedRuleSet-6[0].rules[0].use[1]!/root/go/src/configcenter/src/ui/node_modules/vue-loader/lib/loaders/stylePostLoader.js!/root/go/src/configcenter/src/ui/node_modules/sass-loader/dist/cjs.js??clonedRuleSet-6[0].rules[0].use[2]!/root/go/src/configcenter/src/ui/node_modules/postcss-loader/dist/cjs.js!/root/go/src/configcenter/src/ui/node_modules/sass-resources-loader/lib/loader.js??clonedRuleSet-6[0].rules[0].use[4]!/root/go/src/configcenter/src/ui/node_modules/vue-loader/lib/index.js??vue-loader-options!/root/go/src/configcenter/src/ui/src/components/model-manage/field-group/index.vue?vue&type=style&index=0&id=51830ffa&lang=scss&scoped=true&': No serializer registered for SassError
<w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> SassError
  build [====================] 100% (169.1 seconds)

Build completed in 3.999s

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
     ╷
1325 │       background-color: $ghostBackgroundColor !important
     │                         ^^^^^^^^^^^^^^^^^^^^^
     ╵
  src/components/model-manage/field-group/index.vue 1325:25  root stylesheet
    at processResult (/root/go/src/configcenter/src/ui/node_modules/webpack/lib/NormalModule.js:758:19)
    at /root/go/src/configcenter/src/ui/node_modules/webpack/lib/NormalModule.js:860:5
    at /root/go/src/configcenter/src/ui/node_modules/loader-runner/lib/LoaderRunner.js:400:11
    at /root/go/src/configcenter/src/ui/node_modules/loader-runner/lib/LoaderRunner.js:252:18
    at context.callback (/root/go/src/configcenter/src/ui/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /root/go/src/configcenter/src/ui/node_modules/sass-loader/dist/index.js:54:7
    at Function.call$2 (/root/go/src/configcenter/src/ui/node_modules/sass/sass.dart.js:99624:16)
    at render_closure.call$0 (/root/go/src/configcenter/src/ui/node_modules/sass/sass.dart.js:85029:23)
    at Object.Primitives_applyFunction (/root/go/src/configcenter/src/ui/node_modules/sass/sass.dart.js:1119:30)
    at Object.Function_apply (/root/go/src/configcenter/src/ui/node_modules/sass/sass.dart.js:5257:16)
    at _callDartFunctionFast (/root/go/src/configcenter/src/ui/node_modules/sass/sass.dart.js:23061:16)
    at /root/go/src/configcenter/src/ui/node_modules/sass/sass.dart.js:23039:18
```

重现方法
================
cd $GOPATH/src/configcenter/src/
make ui

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: V3.10.11
 
 - [ ] MongoDB   版本: 
 - [ ] Redis     版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by qiuyanbin** [comment]
请问这个问题是解决了吗？是怎么解决的呢？
