### ISSUE TITLE
3.10.11版本cmdb_cacheservice服务无法正常启动

### ISSUE THREAD

**Issue by yeaheo** [Tencent/bk-cmdb#6212]
问题描述
===========
3.10.11 版本首次部署基本很流畅，没出现什么问题，后来修改了 mongodb、redis 相关中间件的密码，也刷新了配置，但是cmdb_cacheservice 这个服务起不来了，不知道啥情况

重现方法
================
重启 cmdb_cacheservice 服务

关键信息
=========
服务启动报错信息如下：
```bash
begin to discover by watch children of path(/cc/services/endpoints/proc)
begin to discover by watch children of path(/cc/services/endpoints/operation)
begin to discover by watch children of path(/cc/services/endpoints/migrate)
begin to discover by watch children of path(/cc/services/endpoints/task)
begin to discover by watch children of path(/cc/services/endpoints/apiserver)
begin to discover by watch children of path(/cc/services/endpoints/auth)
begin to discover by watch children of path(/cc/services/endpoints/coreservice)
begin to discover by watch children of path(/cc/services/endpoints/cloud)
begin to discover by watch children of path(/cc/services/endpoints/datacollection)
begin to discover by watch children of path(/cc/services/endpoints/host)
begin to discover by watch children of path(/cc/services/endpoints/cacheservice)
begin to discover by watch children of path(/cc/services/endpoints/topo)
begin to discover by watch children of path(/cc/services/endpoints/eventserver)
E0622 11:16:58.320882     277 topology/logic.go:383] get brief biz topology cache refresh interval minutes failed, err: config not found, use default value 15.
F0622 11:16:58.477449     277 event/watch.go:94] mongodb watch failed with conf: {Options:{MajorityCommitted:0xc000e9023a MaxAwaitTime:1s OperationType:<nil> Filter:map[] CollectionFilter:<nil> EventStruct:0xc000e24150 Collection:cc_ModuleBase StartAfterToken:0xc000796020 StartAtTime:1970-01-01/08:00:00 WatchFatalErrorCallback:0xf95fe0 Fields:[]}}, err: (Location40415) BSON field '$changeStream.startAfter' is an unknown field.
goroutine 1702 [running]:
configcenter/src/common/blog/glog.stacks(0xc000244e00, 0xc000c50a00, 0x1af, 0x1fd)
	/mnt/go/src/configcenter/src/common/blog/glog/glog.go:781 +0xb9
configcenter/src/common/blog/glog.(*loggingT).output(0x1c135e0, 0xc000000003, 0xc0001fec40, 0x170126d, 0xe, 0x5e, 0x0)
	/mnt/go/src/configcenter/src/common/blog/glog/glog.go:732 +0x37a
configcenter/src/common/blog/glog.(*loggingT).printf(0x1c135e0, 0x3, 0x12c763f, 0x2c, 0xc00039a060, 0x2, 0x2)
	/mnt/go/src/configcenter/src/common/blog/glog/glog.go:670 +0x153
configcenter/src/common/blog/glog.Fatalf(0x12c763f, 0x2c, 0xc00039a060, 0x2, 0x2)
	/mnt/go/src/configcenter/src/common/blog/glog/glog.go:1180 +0x67
configcenter/src/storage/stream/event.(*Event).Watch.func1(0xc000638080, 0xc0001fb608, 0x14be2b0, 0xc001542040, 0xc000e10240)
	/mnt/go/src/configcenter/src/storage/stream/event/watch.go:94 +0x396
created by configcenter/src/storage/stream/event.(*Event).Watch
	/mnt/go/src/configcenter/src/storage/stream/event/watch.go:35 +0xb4
F0622 11:16:58.629646     277 event/watch.go:94] mongodb watch failed with conf: {Options:{MajorityCommitted:0xc0007b1c88 MaxAwaitTime:1s OperationType:<nil> Filter:map[] CollectionFilter:<nil> EventStruct:0xc00063c040 Collection:cc_ApplicationBase StartAfterToken:0xc0001369f0 StartAtTime:2022-06-14/09:36:46 WatchFatalErrorCallback:0xf6f300 Fields:[]}}, err: (Location40415) BSON field '$changeStream.startAfter' is an unknown field.
```
请提供以下信息:

 - [x] bk-cmdb   版本: 
 ```bash
Version     : 
Tag         : 
BuildTime   : 2022-06-12T10:17:22+0800
GitHash     : 
RunMode     : product
Distribution: community
ServiceName : apiserver
```
 - [x] Redis     版本: 
 ```bash
6.2.7
```
 - [x] MongoDB   版本: 
 ```bash
4.0.27
```
 - [x] ZooKeeper 版本: 
 ```bash
3.8.0
```
 - [x] 操作系统:
 ```bash
CentOS Linux release 7.7.1908 (Core)
```
 - [x] bk-cmdb 异常日志
```bash
internal/poll.(*pollDesc).wait(0xc000174f98, 0x72, 0x0, 0x4, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000174f80, 0xc000ed3f70, 0x4, 0x4, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc000174f80, 0xc000ed3f70, 0x4, 0x4, 0x0, 0x2540be364, 0x7f5bce7379f8)
	/usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000010268, 0xc000ed3f70, 0x4, 0x4, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:183 +0x91
io.ReadAtLeast(0x14a7aa0, 0xc000010268, 0xc000ed3f70, 0x4, 0x4, 0x4, 0x1c13320, 0x15d6d9a8c1e, 0x1c13320)
	/usr/local/go/src/io/io.go:328 +0x87
io.ReadFull(...)
	/usr/local/go/src/io/io.go:347
configcenter/vendor/go.mongodb.org/mongo-driver/x/mongo/driver/topology.(*connection).readWireMessage(0xc0003ebe00, 0x14be2e8, 0xc00003c048, 0xc000b86c00, 0x0, 0x200, 0xc0003ebe00, 0x14be2e8, 0xc00003c048, 0xc000b86c00, ...)
	/mnt/go/src/configcenter/vendor/go.mongodb.org/mongo-driver/x/mongo/driver/topology/connection.go:238 +0x1ef
configcenter/vendor/go.mongodb.org/mongo-driver/x/mongo/driver/topology.initConnection.ReadWireMessage(0xc0003ebe00, 0x14be2e8, 0xc00003c048, 0xc000b86c00, 0x0, 0x200, 0xc000b86c00, 0x105, 0x200, 0x0, ...)
	/mnt/go/src/configcenter/vendor/go.mongodb.org/mongo-driver/x/mongo/driver/topology/connection.go:330 +0x6a
configcenter/vendor/go.mongodb.org/mongo-driver/x/mongo/driver.Operation.roundTrip(0xc000eff3c0, 0x1299ba2, 0x5, 0x14ba2e0, 0xc000eff3d0, 0xc000eff3e0, 0x0, 0x0, 0x0, 0x0, ...)
	/mnt/go/src/configcenter/vendor/go.mongodb.org/mongo-driver/x/mongo/driver/operation.go:521 +0x3e6
configcenter/vendor/go.mongodb.org/mongo-driver/x/mongo/driver.Operation.Execute(0xc000eff3c0, 0x1299ba2, 0x5, 0x14ba2e0, 0xc000eff3d0, 0xc000eff3e0, 0x0, 0x0, 0x0, 0x0, ...)
	/mnt/go/src/configcenter/vendor/go.mongodb.org/mongo-driver/x/mongo/driver/operation.go:345 +0xad9
configcenter/vendor/go.mongodb.org/mongo-driver/x/mongo/driver/operation.(*IsMaster).GetDescription(0xc000235570, 0x14be2e8, 0xc00003c048, 0xc00027f4c0, 0x32, 0x14c4010, 0xc0003ebe00, 0x0, 0x0, 0x0, ...)
	/mnt/go/src/configcenter/vendor/go.mongodb.org/mongo-driver/x/mongo/driver/operation/ismaster.go:418 +0x1f4
configcenter/vendor/go.mongodb.org/mongo-driver/x/mongo/driver/auth.(*authHandshaker).GetDescription(0xc000b1b530, 0x14be2e8, 0xc00003c048, 0xc00027f4c0, 0x32, 0x14c4010, 0xc0003ebe00, 0x0, 0x0, 0x0, ...)
	/mnt/go/src/configcenter/vendor/go.mongodb.org/mongo-driver/x/mongo/driver/auth/auth.go:74 +0x194
configcenter/vendor/go.mongodb.org/mongo-driver/x/mongo/driver/topology.(*connection).connect(0xc0003ebe00, 0x14be2e8, 0xc00003c048)
	/mnt/go/src/configcenter/vendor/go.mongodb.org/mongo-driver/x/mongo/driver/topology/connection.go:123 +0x25a
created by configcenter/vendor/go.mongodb.org/mongo-driver/x/mongo/driver/topology.(*pool).connectionInitFunc
	/mnt/go/src/configcenter/vendor/go.mongodb.org/mongo-driver/x/mongo/driver/topology/pool.go:133 +0xa5
```

**Comment by wcy00000000000000** [comment]
mongodb需要升级到4.2以上，参考部署文档：
https://github.com/Tencent/bk-cmdb/blob/v3.10.x/docs/overview/installation.md
