### ISSUE TITLE
编译的monstache加载plugin报flag redefined

### ISSUE THREAD

**Issue by shenxg13** [Tencent/bk-cmdb#6366]
问题描述
===========
编译的monstache加载plugin报flag redefined

重现方法
================

```
[root@cc01 monstache]# ./monstache -f etc/config.toml 
./monstache flag redefined: v
panic: ./monstache flag redefined: v

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc000144120, 0x7f295b170bc0, 0x7f295b7c3948, 0x7f295ab7bec3, 0x1, 0x7f295ab8b82e, 0x14)
	/usr/local/go/src/flag/flag.go:871 +0x4a5
flag.Var(...)
	/usr/local/go/src/flag/flag.go:886
configcenter/src/common/blog/glog.init.0()
	/data/go/src/configcenter/src/common/blog/glog/glog.go:402 +0x148
plugin.open(0xc000141120, 0x14, 0x0, 0x0, 0x0)
	/usr/local/go/src/plugin/plugin_dlopen.go:101 +0xc1e
plugin.Open(...)
	/usr/local/go/src/plugin/plugin.go:32
main.(*configOptions).loadPlugins(0xc00046e000, 0xc00046e000)
	/data/go/src/monstache-6.7.10/monstache.go:1979 +0x71
main.(*configOptions).build(0xc00046e000, 0xc00046e000)
	/data/go/src/monstache-6.7.10/monstache.go:2424 +0x85
main.mustConfig(0xc000056710)
	/data/go/src/monstache-6.7.10/monstache.go:5094 +0x125
main.main()
	/data/go/src/monstache-6.7.10/monstache.go:5172 +0x34
[root@cc01 monstache]# 
```

```
[root@cc01 monstache]# cat etc/config.toml 
# mongodb settings
mongo-url = "mongodb://aa:aa#@127.0.0.1:27017/cmdb"

# elasticsearch settings
elasticsearch-urls = ["http://127.0.0.1:9200"]
elasticsearch-user = ""
elasticsearch-password = ""
gzip = true

# metadata collections.
change-stream-namespaces = [""]
direct-read-namespaces = [""]
direct-read-dynamic-include-regex = "cmdb.cc_ApplicationBase$|cc_SetBase$|cc_ModuleBase$|cmdb.cc_HostBase$|cmdb.cc_ObjDes$|cc_ObjAttDes$|cmdb.cc_ObjectBase_(.*)_pub_"
namespace-regex = "cmdb.cc_ApplicationBase$|cc_SetBase$|cc_ModuleBase$|cmdb.cc_HostBase$|cmdb.cc_ObjDes$|cc_ObjAttDes$|cmdb.cc_ObjectBase_(.*)_pub_"

# plugin
mapper-plugin-path = "etc/monstache-plugin.so"

# resume mode
resume = true
```

关键信息
=========
cmdb版本：3.10.18
monstache版本：6.7.10
编译后的monstache 6.7.5也报同样的错误

**Comment by lalala2047** [comment]
怎么解决得了？

**Comment by shenxg13** [comment]
> 怎么解决得了？

monstache版本不对，换版本编译。

**Comment by 545119811** [comment]
老铁，你用的monstache哪个版本？
